export interface ProductCategoryItem {
  id: string;
  index: string;
  category: string;
  title: string;
  description: string;
  image: string;
  considerations: string[];
  explanationNote?: string;
}

export const SOLAR_PRODUCT_CATEGORIES: ProductCategoryItem[] = [
  {
    id: 'modules',
    index: '01',
    category: 'Solar Modules',
    title: 'SOLAR MODULES',
    description:
      'Solar modules capture sunlight and convert it into direct-current (DC) electricity for the solar system.',
    image: '/assets/images/products/product-modules.jpg',
    considerations: [
      'High-Yield Cell Efficiency',
      'Power Rating & Tolerance',
      'Mono PERC & TOPCon Tech',
      'PID & Mechanical Load Durability',
    ],
  },
  {
    id: 'inverters',
    index: '02',
    category: 'Solar Inverters',
    title: 'SOLAR INVERTERS',
    description:
      'The inverter converts the electricity generated by solar modules into usable alternating-current (AC) power for the property.',
    image: '/assets/images/products/product-inverters.jpg',
    considerations: [
      'Peak Conversion Performance',
      'String & Central Architecture',
      'Real-Time IoT Cloud Monitoring',
      'Thermal Control & Protection',
    ],
  },
  {
    id: 'bos',
    index: '03',
    category: 'Mounting & BOS',
    title: 'MOUNTING &\nBOS COMPONENTS',
    description:
      'Mounting structures and balance-of-system components support the physical installation and electrical connection of the solar system.',
    image: '/assets/images/products/product-bos.jpg',
    explanationNote: 'BOS = Balance of System (supporting mounting & cabling hardware)',
    considerations: [
      'Hot-Dip Galvanized Steel Rails',
      'UV-Resistant Dual-Core Solar Cables',
      'Certified MC4 Connectors',
      'High Wind Load Compliance',
    ],
  },
  {
    id: 'protection',
    index: '04',
    category: 'System Protection',
    title: 'SYSTEM PROTECTION',
    description:
      'Electrical protection components help support safe and reliable operation of the solar installation.',
    image: '/assets/images/products/product-protection.jpg',
    considerations: [
      'ACDB & DCDB Distribution Boxes',
      'Type-2 Surge Protection Devices',
      'Dedicated Chemical Earthing',
      'Grid Isolation & MCB Controls',
    ],
  },
];
